### ISSUE TITLE
Blank screen upon impact

### ISSUE THREAD

**Issue by itpropaul** [ehmorris/lunar-lander#34]
I may have stumbled across a bug. 

Finally figured out how to use the HUD and started planning my descent soon after I crossed 1 Million feet height. 

Was over 10,000 MPH and had flown over 2 Million feet high. 

At the moment of impact (0 feet height), GUI just went blank and would still periodically update total bonus and new speed records as shown in the screenshot. 

This was on Android 13 Chrome 112

![image](https://user-images.githubusercontent.com/30813009/234957835-c491e175-82bc-4802-8e5d-23694659bfe5.png)

**Comment by ehmorris** [comment]
Thanks for the report. This will be a tricky one to reproduce. At a glance I can't see why [this block](https://github.com/ehmorris/lunar-lander/blob/master/lander/lander.js#L173C45-L176) wouldn't catch it. But I'll bet this has something to do with the `velocity.y` being very very high. I'll try to look into it.

Can you give me any information about your device? Has this happened any other times?

**Comment by itpropaul** [comment]
@ehmorris My pleasure! I'll say that I did a similar trip on Chrome on Mac laptop and didn't experience the same bug.

Regarding the device, for the sake of operational security, I'd rather not share more.

I probably won't do similar trips in the future and instead focus on dialing in landings :D, but figured for other souls out there that wanted to do the same, it'd be good to report.

Thanks so much for creating this game. It's pretty incredible what you've done with pure html, css, and javascript!

**Comment by Prehistoricman** [comment]
I'm getting this issue sporadically on Brave. This is the error in the console.

Uncaught TypeError: DD_RUM.addAction is not a function
    at _setGameEndData (lander.js:170:12)
    at _updateProps (lander.js:307:7)
    at Object.draw (lander.js:574:7)
    at index.js:168:12
    at drawFuncContainer (helpers.js:32:5)

**Comment by ehmorris** [comment]
Ah, thank you. That's a recent addition. I'm guessing Datadog's scripts are being blocked. If I check for DD_RUM first that may solve this problem

**Comment by ehmorris** [comment]
This should fix that error: https://github.com/ehmorris/lunar-lander/commit/a80cc9c2e23beb434fde046e2381b6e7877390da

**Comment by ehmorris** [comment]
That didn't work but this should: https://github.com/ehmorris/lunar-lander/commit/a294de5ccc63c3317d48f6915eab85f1c4c7e4cb

**Comment by ehmorris** [comment]
Confirmed
